import { SCOPE_ANALYSIS_JSON_SCHEMA, SCOPE_ANALYSIS_SCHEMA_NAME } from "@/lib/ai/json-schema";
import { ANALYSIS_INSTRUCTION, buildSystemPrompt } from "@/lib/ai/prompt";
import { FALLBACK_BETA } from "@/lib/ai/models";
import { code, config, http, ifNode, noop, reportEvent, respond, sticky, telegram, webhook, WorkflowBuilder } from "../builder";
import { ESCAPE_JS } from "../snippets";

const NAME = "ASD 02 · AI Scope & Budget Analysis";

/**
 * JavaScript twin of `buildUserMessage()` in src/lib/ai/prompt.ts.
 * tests/n8n-workflows.test.ts executes it and asserts identical output.
 */
export const USER_MESSAGE_JS = String.raw`function buildUserMessage(brief, options) {
  options = options || {};
  var parts = [ANALYSIS_INSTRUCTION, "", "<brief>", JSON.stringify(brief, null, 2), "</brief>"];
  if (options.previous) {
    parts.push(
      "",
      "<previous_analysis>",
      "Project type: " + options.previous.projectType + ". Recommended investment: " + options.previous.recommended + ". Timeline: " + options.previous.totalWeeks + " weeks.",
      "</previous_analysis>"
    );
  }
  var instructions = options.instructions ? String(options.instructions).trim() : "";
  if (instructions) {
    parts.push(
      "",
      "<revision_request>",
      "The studio team (not the client) asked for a revised analysis with this direction:",
      instructions,
      "</revision_request>"
    );
  }
  return parts.join("\n");
}`;

export function promptConstantsJs(): string {
  return [
    `const SYSTEM_PROMPT = ${JSON.stringify(buildSystemPrompt())};`,
    `const ANALYSIS_INSTRUCTION = ${JSON.stringify(ANALYSIS_INSTRUCTION)};`,
    `const OUTPUT_SCHEMA = ${JSON.stringify(SCOPE_ANALYSIS_JSON_SCHEMA)};`,
    `const SCHEMA_NAME = ${JSON.stringify(SCOPE_ANALYSIS_SCHEMA_NAME)};`,
  ].join("\n");
}

export const BUILD_REQUEST_JS = () =>
  "// Generated by `npm run n8n:build` from src/lib/ai/prompt.ts + src/config/catalog.ts — edit there, or tweak here.\n" +
  promptConstantsJs() +
  "\n" +
  USER_MESSAGE_JS +
  String.raw`

const body = $('Analysis Webhook').first().json.body;
const cfg = $('Config').first().json;
const user = buildUserMessage(body.lead.aiBrief, { instructions: body.instructions, previous: body.previous });
const model = cfg.anthropicModel;
const adaptive = !/haiku/i.test(model);
const fallback = /^claude-(opus-5|fable-5|mythos-5)/.test(model) && String(cfg.anthropicBeta || "").indexOf("server-side-fallback") !== -1;

const anthropicBody = {
  model: model,
  max_tokens: 16000,
  system: [{ type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } }],
  messages: [{ role: "user", content: user }],
  output_config: Object.assign(adaptive ? { effort: cfg.effort } : {}, { format: { type: "json_schema", schema: OUTPUT_SCHEMA } }),
};
if (adaptive) anthropicBody.thinking = { type: "adaptive" };
if (fallback) anthropicBody.fallbacks = "default";

const openaiBody = {
  model: cfg.openaiModel,
  max_completion_tokens: 32000,
  messages: [{ role: "system", content: SYSTEM_PROMPT }, { role: "user", content: user }],
  response_format: { type: "json_schema", json_schema: { name: SCHEMA_NAME, strict: true, schema: OUTPUT_SCHEMA } },
};

return [{ json: { leadId: body.lead.id, reference: body.lead.reference, provider: cfg.aiProvider, anthropicBody, openaiBody, instructions: body.instructions || null, startedAt: Date.now() } }];`;

const PARSE_JS = String.raw`// Normalises Claude / OpenAI responses into { ok, analysis, provider, model, usage } or { ok: false, error }.
const r = $json;
const req = $('Build AI Request').first().json;
const fail = (error) => [{ json: { ok: false, error, leadId: req.leadId, reference: req.reference } }];
let text = "", provider = req.provider, model = null, usage = null;

if (Array.isArray(r.content)) {
  provider = "anthropic";
  // Check the stop reason before reading content: refusals / truncation may not match the schema.
  if (r.stop_reason === "refusal") return fail("Claude declined the request" + (r.stop_details && r.stop_details.category ? " (" + r.stop_details.category + ")" : ""));
  if (r.stop_reason === "max_tokens") return fail("Claude's response was truncated (max_tokens)");
  text = r.content.filter((b) => b.type === "text").map((b) => b.text).join("");
  model = r.model; usage = r.usage;
} else if (Array.isArray(r.choices)) {
  provider = "openai";
  const choice = r.choices[0] || {};
  if (choice.message && choice.message.refusal) return fail("OpenAI declined: " + choice.message.refusal);
  if (choice.finish_reason === "length") return fail("OpenAI response was truncated (length)");
  text = (choice.message && choice.message.content) || "";
  model = r.model; usage = r.usage;
} else {
  return fail("Unrecognised AI response: " + JSON.stringify(r).slice(0, 300));
}

let analysis;
try { analysis = JSON.parse(text); } catch (e) { return fail("Model output was not valid JSON"); }
if (!analysis || !Array.isArray(analysis.deliverables) || !analysis.timeline || !analysis.budget) return fail("Model output is missing required sections");
// The app re-validates and normalises the analysis (totals, phases, clamping) on POST /api/v1/proposals.
return [{ json: { ok: true, analysis, provider, model, usage, leadId: req.leadId, reference: req.reference, durationMs: Date.now() - req.startedAt } }];`;

export function aiScopeAnalysisWorkflow() {
  const wf = new WorkflowBuilder(
    NAME,
    "Receives `analysis.requested`, runs the scope & budget analysis on Claude (default) or OpenAI with structured outputs, and posts the result to POST /api/v1/proposals, which builds the proposal draft.",
    ["AS Design Studio", "AI"],
  );

  wf.add(
    sticky("Note · Overview", [-480, -300], [
      "## 02 · AI Scope & Budget Analysis",
      "**Trigger:** the app POSTs `analysis.requested` for every new lead and every *Regenerate* click.",
      "",
      "1. **Build AI Request** assembles the system prompt (studio rate card), the data-minimised brief (no contact details) and the JSON schema — generated from the app's source, so both runners behave identically",
      "2. **Claude** (`claude-opus-5`, adaptive thinking, structured outputs, server-side refusal fallback) or **OpenAI** (strict `json_schema`)",
      "3. **Parse** checks the stop reason and JSON",
      "4. **Submit to App** → `POST /api/v1/proposals` (idempotent per execution) → proposal draft appears live in the dashboard",
      "5. Telegram: *draft ready for review* — or a failure alert + `analysis.failed` event",
      "",
      "**Credentials:** *ASD · Anthropic API key* (Header Auth · name `x-api-key`), *ASD · OpenAI API key* (Header Auth · `Authorization: Bearer …`), *ASD · App API*, *ASD · Telegram bot*.",
    ].join("\n"), { width: 440, height: 440 }, 6),
  );

  wf.add(webhook("Analysis Webhook", "asd-ai-analysis", [0, 0], NAME));
  wf.add(respond("Respond 202", [220, 0], "={{ JSON.stringify({ accepted: true, executionId: $execution.id }) }}"));
  wf.add(
    config("Config", [440, 0], [
      { name: "appBaseUrl", value: "https://automation.asdesignlb.com" },
      { name: "aiProvider", value: "anthropic" },
      { name: "anthropicModel", value: "claude-opus-5" },
      { name: "anthropicBeta", value: FALLBACK_BETA },
      { name: "effort", value: "high" },
      { name: "openaiModel", value: "gpt-5.5" },
      { name: "telegramChatId", value: "REPLACE_WITH_TELEGRAM_CHAT_ID" },
    ], NAME),
  );
  wf.add(ifNode("Is test ping?", [660, 0], { left: "={{ $('Analysis Webhook').first().json.body.type }}", op: "equals", right: "test.ping" }, NAME));
  wf.add(noop("Test OK", [880, -140]));
  wf.add(code("Build AI Request", [880, 60], BUILD_REQUEST_JS()));
  wf.add(ifNode("Use OpenAI?", [1100, 60], { left: "={{ $json.provider }}", op: "equals", right: "openai" }, NAME));

  wf.add({
    ...http("Claude · Messages API", [1320, 160], {
      url: "https://api.anthropic.com/v1/messages",
      auth: "anthropic",
      headers: [
        { name: "anthropic-version", value: "2023-06-01" },
        { name: "anthropic-beta", value: "={{ $('Config').first().json.anthropicBeta }}" },
      ],
      jsonBody: "={{ JSON.stringify($json.anthropicBody) }}",
      timeout: 600_000,
      errorOutput: true,
    }),
    waitBetweenTries: 10_000,
  });
  wf.add({
    ...http("OpenAI · Chat Completions", [1320, -40], {
      url: "https://api.openai.com/v1/chat/completions",
      auth: "openai",
      jsonBody: "={{ JSON.stringify($json.openaiBody) }}",
      timeout: 600_000,
      errorOutput: true,
    }),
    waitBetweenTries: 10_000,
  });

  wf.add(code("Parse AI Response", [1560, 60], PARSE_JS));
  wf.add(code("Capture HTTP Error", [1560, 300], String.raw`const req = $('Build AI Request').first().json;
const err = $json.error || {};
const message = (err.message || err.description || JSON.stringify($json).slice(0, 300));
return [{ json: { ok: false, error: "AI provider request failed: " + message, leadId: req.leadId, reference: req.reference } }];`));
  wf.add(ifNode("Analysis OK?", [1780, 60], { left: "={{ $json.ok }}", op: "true" }, NAME));

  wf.add(
    http("Submit to App", [2000, -20], {
      url: "={{ $('Config').first().json.appBaseUrl }}/api/v1/proposals",
      auth: "appApi",
      headers: [{ name: "Idempotency-Key", value: "={{ 'n8n-' + $execution.id }}" }],
      jsonBody:
        "={{ JSON.stringify({ leadId: $json.leadId, analysis: $json.analysis, provider: $json.provider, model: $json.model, usage: $json.usage, durationMs: $json.durationMs, instructions: $('Build AI Request').first().json.instructions }) }}",
      timeout: 60_000,
    }),
  );
  wf.add(
    code("Format Ready Alert", [2220, -20], ESCAPE_JS + String.raw`
const res = $json;
const p = res.proposal;
const text = [
  "<b>✨ Proposal draft ready · " + esc(res.lead.reference) + "</b>",
  esc(p.title),
  "💰 " + esc(p.display.total) + (p.display.monthly ? " + " + esc(p.display.monthly) : "") + " · " + esc(p.display.duration),
  "",
  '<a href="' + esc(res.links.admin) + '">Review & approve →</a>',
].join("\n");
return [{ json: { text } }];`),
  );
  wf.add(telegram("Telegram · Draft Ready", [2440, -20], "={{ $json.text }}"));

  wf.add(
    code("Format Failure", [2000, 200], ESCAPE_JS + String.raw`
const f = $json;
return [{ json: { leadId: f.leadId, error: f.error, text: "⚠️ <b>AI analysis failed · " + esc(f.reference) + "</b>\n" + esc(f.error) + "\nThe lead is back in the dashboard — use Regenerate to retry." } }];`),
  );
  wf.add(reportEvent("Report Failure", [2220, 200], "{ type: 'analysis.failed', leadId: $('Format Failure').first().json.leadId, data: { error: $('Format Failure').first().json.error, executionId: $execution.id } }"));
  wf.add(telegram("Telegram · Failure", [2440, 200], "={{ $('Format Failure').first().json.text }}"));

  wf.chain("Analysis Webhook", "Respond 202", "Config", "Is test ping?");
  wf.connect("Is test ping?", "Test OK", 0);
  wf.connect("Is test ping?", "Build AI Request", 1);
  wf.connect("Build AI Request", "Use OpenAI?");
  wf.connect("Use OpenAI?", "OpenAI · Chat Completions", 0);
  wf.connect("Use OpenAI?", "Claude · Messages API", 1);
  wf.connect("OpenAI · Chat Completions", "Parse AI Response", 0);
  wf.connect("OpenAI · Chat Completions", "Capture HTTP Error", 1);
  wf.connect("Claude · Messages API", "Parse AI Response", 0);
  wf.connect("Claude · Messages API", "Capture HTTP Error", 1);
  wf.connect("Parse AI Response", "Analysis OK?");
  wf.connect("Capture HTTP Error", "Analysis OK?");
  wf.connect("Analysis OK?", "Submit to App", 0);
  wf.connect("Analysis OK?", "Format Failure", 1);
  wf.connect("Format Failure", "Report Failure");
  wf.chain("Submit to App", "Format Ready Alert", "Telegram · Draft Ready");
  wf.connect("Report Failure", "Telegram · Failure");

  return wf.build();
}
